In [1]:
!nvidia-smi

Wed Jun 30 12:25:42 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:88:00.0 Off |                    0 |
| N/A   30C    P0    40W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
from hdmf.common import get_hdf5io
import numpy as np
from fastai.text.all import *

In [3]:
import h5py

In [4]:
path = Path('../taxon_trials')
path.ls()

(#27) [Path('../taxon_trials/pytorch_train_loop.ipynb'),Path('../taxon_trials/.gitignore'),Path('../taxon_trials/effnet_redux.ipynb'),Path('../taxon_trials/LICENSE'),Path('../taxon_trials/effnet_initial.ipynb'),Path('../taxon_trials/data'),Path('../taxon_trials/effnet_test.ipynb'),Path('../taxon_trials/README.md'),Path('../taxon_trials/cori_output'),Path('../taxon_trials/test_fastai.ipynb')...]

In [5]:
path = '../taxon_trials/ar122_r202.rep.h5'

In [6]:
f1 = h5py.File(path, 'r')
print(list(f1.keys()))

['distances', 'genome_table', 'seq_table', 'specifications', 'taxa_table', 'tree', 'tree_graph']


In [7]:
f = h5py.File(path, 'r')

In [12]:
f['seq_table'].keys()

<KeysViewHDF5 ['genome', 'id', 'length', 'sequence', 'sequence_elements', 'sequence_index', 'sequence_name']>

In [30]:
f['seq_table']['sequence_elements'][:]

array([b'A', b'C', b'Y', b'W', b'S', b'K', b'D', b'V', b'N', b'T', b'G',
       b'R', b'W', b'S', b'M', b'H', b'B', b'N'], dtype=object)

In [19]:
f['seq_table']['sequence_name']

<HDF5 dataset "sequence_name": shape (237240,), type "|O">

In [46]:
f['seq_table']['sequence_name'][:10]

array([b'DP000238.1', b'CP003316.1', b'CP003317.1', b'CP003083.1',
       b'AQVQ01000001.1', b'AQVQ01000002.1', b'AQVQ01000003.1',
       b'AQVQ01000004.1', b'AQVQ01000005.1', b'AQVQ01000006.1'],
      dtype=object)

In [41]:
f['seq_table']['sequence'][:5]

array([9, 0, 0, 9, 1], dtype=uint8)

In [49]:
f['seq_table']['sequence'].shape

(4610956683,)

In [65]:
np.unique(f['seq_table']['sequence'][:100000000])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14, 15, 16],
      dtype=uint8)

In [20]:
f['distances'][:].shape

(2339, 2339)

In [22]:
f['genome_table'].keys()

<KeysViewHDF5 ['id', 'rep_idx', 'taxon_id']>

In [26]:
f['genome_table']['id'][:].shape

(2339,)

In [28]:
f['genome_table']['taxon_id'][:]

array([b'GCA_000200715.1', b'GCA_000247545.1', b'GCA_000306725.1', ...,
       b'GCF_013390375.1', b'GCF_900109065.1', b'GCF_900114585.1'],
      dtype=object)

In [31]:
f['tree_graph'].keys()

<KeysViewHDF5 ['data', 'indices', 'indptr', 'leaves']>

In [34]:
f['tree_graph']['data'][:]

array([0.02101, 0.02197, 0.00559, ..., 0.22193, 0.46273, 0.46273])

In [17]:
f['tree_graph']['leaves']

<HDF5 dataset "leaves": shape (4677,), type "<i8">

In [19]:
f['genome_table'].keys()

<KeysViewHDF5 ['id', 'rep_idx', 'taxon_id']>

In [8]:
f['tree']

<HDF5 dataset "tree": shape (), type "|O">